### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by hugok79** [BodhiDev/Bodhi-themes#3]
Icon in "About Bodhi Linux" is missing with MoshkaDimensions theme selected. But also in Default theme, Moksha WoodGrey, Moksha Pink, Moksha KL4K, Moksha Japan, Moksha Ice, Moksha Forum and Moksha ArcDark.

![shot-2023-07-21_20-33-42](https://github.com/BodhiDev/Bodhi-themes/assets/16929048/7811c489-64b0-42ff-9f84-6fd84e1068df)

**Comment by thewaiter** [comment]
https://github.com/thewaiter/MokshaDimensions/commit/203d3033188cbf62f70b832227ebfc82ae2405df�

Fixed Dimension theme. I will fix another ones tomorrow. Thanx for the report

**Comment by rbtylee** [comment]
I will update the deb file in BL7 repos sometime this weekend.
